apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-rootsync
  name: edge03-rootsync
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-rootsync'
spec:
  annotations:
    approval.nephio.org/policy: initial
    approval.nephio.org/delay: 2m
  upstream:
    package: rootsync
    repo: nephio-example-packages
    revision: v3
  downstream:
    package: edge03-rootsync
    repo: mgmt-staging
  injectors:
  - kind: WorkloadCluster
    name: edge03
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: edge03
