apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-configsync
  name: cluster01-configsync
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-configsync'
spec:
  upstream:
    package: configsync
    repo: demo-packages
    revision: v1
  downstream:
    package: cluster01-configsync
    repo: mgmt-staging
  packageContext:
    data:
      siteName: cluster01
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/site: cluster01
