apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-repo
  name: cluster01-repo
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-repo'
spec:
  upstream:
    package: repo
    repo: demo-packages
    revision: v1
  downstream:
    package: cluster01-repo
    repo: mgmt
