apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-rootsync
  name: cluster01-rootsync
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-rootsync'
spec:
  upstream:
    package: rootsync
    repo: demo-packages
    revision: v1
  downstream:
    package: cluster01-rootsync
    repo: mgmt-staging
