apiVersion: infra.nephio.org/v1alpha1
kind: Repository
metadata: # kpt-merge: default/example-site-name
  name: default
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: infra.nephio.org|Repository|default|example-site-name
spec:
  description: default repository
  defaultBranch: main
